### PR TITLE
build: publish ESM and .d.ts

### LINKED ISSUE #25: ES Module
Please publish as an ES Module.

If users need CJS, it could be compiled from the standard javascript.

### PR DESCRIPTION
**Pull request by cometkim**
- Upgraded dependencies
- Fixed the macro
- Fixed publish configs to includes macro as well
- Added TypeScript declaration files
- Made it leaves Flow type definitions as comments
- Added ESM (modern target) build, resolves #25

### CODE REVIEW

**Comment by cometkim** [comment]
Published the fork as [@cometlib/dedent](https://npm.im/@cometlib/dedent)

**Comment by adrianjost** [comment]
Hi @cometkim would you mind opening this PR also against [dedent-tabs](https://www.npmjs.com/package/dedent-tabs) which is a version of this project that I still actively maintain and were I keep all dependencies up to date.
I think it would be better if we have fewer published forks so other users do not have to look into a bunch of them and have to decide which updated version they want.
Here is the repo: https://github.com/adrianjost/dedent-tabs

**Comment by otakustay** [comment]
We need to manually add `types` field to `package.json`, Upcoming TypeScript 4.6's `nodenext` module resolution won't resolve `index.d.ts` automatically

Also, for `dedent/macro` to work with TypeScript 4.6, we need `exports` mapping in `package.json`

**Comment by otakustay** [comment]
Do we have a ETA on this? We heavily rely on this fantasy library but have some problems using it in pure ESM environment.

**Review by JoshuaKGoldberg — COMMENTED** [review]
There's a lot of great stuff in here (package bumps! TypeScript types! yay!) but it's hard to take action on a PR that's got so many unrelated things. 🤔

I'll take on some of the discrete parts in order separately. Then will update this PR once those are in.

**Comment by JoshuaKGoldberg** [comment]
Superceded by #38. I added co-author credit there. Thanks for getting this started! ❤️

**Comment by JoshuaKGoldberg** [comment]
@cometkim I merged #38's changes into this branch. Do these look good to you?

I'll merge this as-is Soon™️ (say, a couple weeks) if you don't have a chance to take a look, no worries if you can't!

**Review by JoshuaKGoldberg — APPROVED** [review]
🚀 let's ship this!

**Pull request merged**
