### PR TITLE
feat(macro): add a /macro for babel-macros

### LINKED ISSUE #18: Support babel-macros
It would be nice to have this at build time instead of runtime, would you be open to a PR adding `/macro.js` with glue code for babel-plugin-macros? I'll gladly make that PR 😄 

cc @kentcdodds

### PR DESCRIPTION
**Pull request by Haroenv**
fixes #18

cc @kentcdodds @satya164

### CODE REVIEW

**Comment by Haroenv** [comment]
some usage can also be added

**Comment by Haroenv** [comment]
@dmnd do you like this feature?

**Comment by dmnd** [comment]
@Haroenv yes, I like the idea! 

I'll make some time to review dedent PRs this weekend. I've been quite absentee recently. Sorry!

**Comment by Haroenv** [comment]
Feel free to ask me if you need help maintaining it

**Comment by Haroenv** [comment]
@dmnd friendly ping 😃

**Comment by dmnd** [comment]
Looks great, @Haroenv. Sorry for the long delay. I'll add you as a maintainer! :tada:

**Comment by dmnd** [comment]
I haven't used babel macros myself, but this seems really cool. Thanks for contributing. My only nitpick is that I think you have prettier set up differently than I do. Want to fix that then merge yourself?

**Comment by Haroenv** [comment]
Ah, that must have been a mistake. I’ll get it consistent and merge :)

**Comment by olsonpm** [comment]
I only learned about babel-macros today and noticed this wasn't published to npm.  I have no problems depending on the github version, but would be convenient for others if you published it when time permits.

Thanks so much for the code :+1:

**Comment by kentcdodds** [comment]
You're looking for [babel-plugin-macros](https://www.npmjs.com/package/babel-plugin-macros) I think. It has been published, is gaining in traction and use, and is actively maintained.

**Comment by Haroenv** [comment]
@kentcdodds, I think @olsonpm means that this PR hasn’t been released yet, which is true. Nice to hear it works for you :). @dmnd, could you cut a release?

**Pull request merged**
